# Generated by Django 4.2.11 on 2025-06-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='customer_qr_codes/'),
        ),
    ]
