# Generated by Django 4.2.11 on 2025-06-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_partial_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'En proceso'), ('READY', 'Listo para recoger'), ('CANCELLED', 'Anulado')], default='PROCESSING', max_length=20),
        ),
    ]
