# Generated by Django 4.2.11 on 2025-06-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_sale_alter_order_status_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
