# Generated by Django 4.2.11 on 2025-06-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_order_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appconfiguration',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='adjusted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Ajustado'),
        ),
    ]
