# Generated by Django 4.2.11 on 2025-06-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_appconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto de descuento aplicado al pedido.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='original_calculated_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio calculado automáticamente basado en el peso y categorías.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='price_adjusted_by_user',
            field=models.BooleanField(default=False, help_text='Indica si el precio final fue ajustado manualmente por un usuario.'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
