# Generated by Django 4.2.11 on 2025-06-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='short_id',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campo técnico para resolver error de constraint.', max_digits=10, null=True),
        ),
    ]
