# Generated by Django 4.2.11 on 2025-07-02 01:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_productcategory_order_barcode_sale_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('category', models.CharField(choices=[('INSUMOS', 'Insumos (Detergente, Suavizante, etc.)'), ('SERVICIOS', 'Servicios Públicos (Agua, Luz, Internet)'), ('SUELDOS', 'Sueldos y Salarios'), ('ALQUILER', 'Alquiler del Local'), ('MARKETING', 'Marketing y Publicidad'), ('MANTENIMIENTO', 'Mantenimiento de Equipo'), ('OTROS', 'Otros Gastos')], max_length=50, verbose_name='Categoría')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Gasto')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/receipts/', verbose_name='Comprobante')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-expense_date'],
            },
        ),
    ]
